# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Main
    url: /
    weight: 10
  - name: News
    url: /#papers
    weight: 11
  - name: Team
    url: /#talks
    weight: 12
  - name: Research
    url: /#news
    weight: 13
  - name: Publications
    url: experience/
    weight: 20
  - name: Gallery
    url: projects/
    weight: 30
  - name: Contact
    url: courses/
    weight: 40
