# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Main
    url: /
    weight: 10
  - name: News
    url: /#News
    weight: 11
  - name: Team
    url: Team/
    weight: 12
  - name: Research
    url: Research/
    weight: 13
  - name: Publications
    url: Publications/
    weight: 20
  - name: Gallery
    url: Gallery/
    weight: 30
  - name: Contact
    url: /#Contact
    weight: 40
